//Even Fibonacci numbers
//Problem 2
//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.
#include <conio.h>
#include <stdio.h>

int main()
{
	double result = 0;
	int current = 0;
	int prev = 0;
	int upValue = 4e+6;
	for (int i = 1; i < upValue; i += current){
		prev = current;
		current = i + prev;
		if (current % 2 == 0){
			result += current;
		}
		if (i % 2 == 0){
			result += i;
		}
	}
	printf("%lf", result);
	_getch();
	return 0;
}